FROM ubuntu
  
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt install -y python3-dev python3-pip  python3-opencv vim-tiny  libopencv-dev
RUN apt install -y mosquitto-clients
RUN apt install -y curl
RUN apt install -y unzip
RUN apt install -y vim
RUN pip3 install Cython
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install paho-mqtt
RUN pip3 install torch==1.4.0
RUN pip3 install scikit-learn
RUN pip3 install matplotlib
